### ISSUE TITLE
Using images inside node_modules

### ISSUE THREAD

**Issue by silva96** [rails/cssbundling-rails#120]
Context:

Using Propshaft, cssbundling-rails, jsbundling-rails, esbuild

I'm using a npm plugin that has a css like this:

```css
// node_modules/the_module/build/css/styles.css

.some-div {
  background: url('../img/icon.png')
}
```

the background refers to

`node_modules/the_module/build/img/icon.png`

In my application.scss I have

`@import 'the_module/build/css/styles';`

The css file gets included in my precompiled application.css but it tries to find an image in localhost:3000/img/icon.png which of course does not exist.

How can I make that image available under assets?
